-- AlterTable Goal
ALTER TABLE "Goal" ADD COLUMN IF NOT EXISTS "linkedTaskNames" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Goal" ADD COLUMN IF NOT EXISTS "targetCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable Task
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
